### Ex1

dataset <- read.table('weather.txt', header=T)



n <- dim(dataset)[1]
p <- dim(dataset)[2]


# Boxplot
x11()
boxplot(dataset, las=2, col='gold')


# Boxplot centered in the means
x11()
boxplot(scale(x=dataset,center = T, scale=F), las=2, col='gold')



dataset <- scale(dataset)  # the default command is with center=T and scale= T 
dataset <- data.frame(dataset)
# oppure centra le variabili
# dataset = data.frame(scale(data = dataset, center = T, scale = F))

# boxplot of the scaled variables 
x11()
boxplot(dataset, las=2, col='gold')


# PCA
pc.dataset <- princomp(dataset, scores=T)
pc.dataset
summary(pc.dataset)

# Matrix of the loading
load <- pc.dataset$loadings  
load

k = 3
x11()
par(mar = c(1,k,0,2), mfrow = c(k,1))
for(i in 1:k) barplot(load[,i], ylim = c(-1, 1))


threshold = 0.3
k = 3 # number of PC we select
x11()
par(mar = c(1,k,0,2), mfrow = c(k,1))
for(i in 1:k) {
  barplot(ifelse(abs(load[,i]) < threshold, 0, load[,i]) , ylim = c(-1, 1))
  abline(h=0)
}


# b)
# Scores
scores.dataset <- pc.dataset$scores

x11()
plot(scores.dataset[,1:2])
abline(h=0, v=0, lty=2, col='grey')


x11()
par(mfrow=c(1,1))
plot(scores.dataset[,1],scores.dataset[,2],type="n",xlab="pc1",ylab="pc2", asp=1, xlim=c(-4,3))
text(scores.dataset[,1],scores.dataset[,2],dimnames(dataset)[[1]], cex=0.7)
abline(h = 0)
abline(v = 0)

x11()
biplot(pc.dataset)



# Explained variance
max1 = max(pc.dataset$scores)   # va bene così?
max2 = max(sapply(dataset,sd)^2)
x11()
layout(matrix(c(2,3,1,3),2,byrow=T))
plot(pc.dataset, las=2, main='Principal components', ylim=c(0,max1))
abline(h=1, col='blue')
barplot(sapply(dataset,sd)^2, las=2, main='Original Variables', ylim=c(0,max2), ylab='Variances')
plot(cumsum(pc.dataset$sd^2)/sum(pc.dataset$sd^2), type='b', axes=F, xlab='number of components', 
     ylab='contribution to the total variance', ylim=c(0,1))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')  #0.8 is a good treshold
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(dataset),labels=1:ncol(dataset),las=2)


# proportion of variance explained by each PC
pc.dataset$sd^2/sum(pc.dataset$sd^2)

cumsum(pc.dataset$sd^2)/sum(pc.dataset$sd^2)


##

# Projection on the space generated by the first k principal components
k = 3

# il primo agosto è il primo giorno non nel dataset
new_obs = c(30,23,36,22,0.65,19,5,15)
x11(width=21, height=7)
par(mfrow=c(2,5))
matplot(t(new_obs), type='l', main = 'Data')

meanF <- colMeans(dataset)
matplot(meanF, type='l', main = '0 PC', lwd=2)
for(i in 1:8)
{
  projection <- matrix(meanF, dim(new_obs)[1], byrow=T) + scores.dataset[,i] %*% t(load[,i])
  matplot(t(projection), type='l', main = paste(i, 'PC'))
  matplot(meanF, type='l', lwd=2, add=T)
}


## ?


# Project a new datum on span(PC1,...,PCk)

x0 = c(30,23,36,22,0.65,19,5,15)    # vector in R^p 

x0 %*% load[ , 1]   # projection on span(PC1)
x0 %*% load[ , 2]   # projection on span(PC2)
x0 %*% load[ , 3] 
#...

x0 %*% load[ , 1:3]   # projection on span(PC1,...,PCk)








