X <- read.table("~/GitHub/Applied-Statistics-Exam//Exams of previous years/2017/2017-07-18/tourists.txt")
# X <- read.table("~/GitHub/Applied-Statistics-Exam//Exams of previous years/2022/2022-02-09/nutrients.txt", header=TRUE)

# a) Scaling
X.numeric <- X[-c(1, 2)]
boxplot(X.numeric)
X.scaled <- scale(X.numeric)
boxplot(X.scaled)

# b) PCA
pca <- princomp(X.scaled)
summary(pca)
loadings <- pca$loadings
loadings
loadings[, 1]
x11()
par(mfrow = c(3, 1))
barplot(loadings[, 1], main = "1st")
barplot(loadings[, 2], main = "2nd")
barplot(loadings[, 3], main = "3rd")

# c) Plot first two scores
x11()
plot(pca$scores[, 1], pca$scores[, 2])
abline(h = 0, v = 0, lty = 2, col = "grey")

# c.1) Color based on a factor (e.g Months)
table(X$Month) # balanced
col.month <- factor(X$Month, labels = rainbow(12))
plot(pca$scores[, 1], pca$scores[, 2], col = col.month, pch = 19)
# text(tourists.pca$scores[,1],tourists.pca$scores[,2],labels = tourists$Month, cex=0.75)
abline(h = 0, v = 0, lty = 2, col = "grey")
legend("topright", levels(as.factor(X[, 1])), fill = rainbow(12), bty = "n")

# d) Screeplot (plot of cumulative variance explained)
x11()
plot(
    cumsum(pca$sdev^2) / sum(pca$sde^2),
    type = "b",
    xlab = "number of components",
    ylab = "contribution to the total variance",
    ylim = c(0, 1)
)
abline(h = 0.8, col = "grey")
var.explained <- pca$sdev^2

# Project a new sample on the space generated by the chosen principal components
x0 <- rbind(400, 9, 5, 100, 30, 4)
x0.scaled <- (x0 - sapply(X.numeric, mean)) / sapply(X.numeric, sd)
score <- t(loadings) %*% x0.scaled
score
